### ISSUE TITLE
Can't open compendium in 1.20.1

### ISSUE THREAD

**Issue by theavandiepen** [CammiesCorner/Arcanus#10]
The contents of the book need to be moved as per https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120

Also, use_resource_pack: true needs to be added to book.json

Otherwise, you can't open the compendium and the logs show an error telling you to make these changes.

The compendium also doesn't have any entries available when you first open it, but if that's intentional, please ignore that- this is my first time using the mod, so I'm not sure how the unlock process is supposed to work xD

**Comment by UpcraftLP** [comment]
Thanks for reporting, Patchouli wasn't yet updated to 1.20 when Arcanus was ported

**Comment by theavandiepen** [comment]
Ahhh that would explain it! And no problem; I’m just glad they made it really easy to figure out what was going on and what needed to be done 😊

**Comment by UpcraftLP** [comment]
fixed in v0.101.0

**Comment by theavandiepen** [comment]
Thanks for such a quick fix!
