### ISSUE TITLE
Latest version causes crash on startup

### ISSUE THREAD

**Issue by theavandiepen** [CammiesCorner/Arcanus#11]
I updated to the latest version for 1.20.1 and when I tried to start up Minecraft, it crashed, and the crash report indicates that Arcanus Continuum is the problem :(

[crash-2023-10-10_14.28.51.9147-quilt_loader.txt](https://github.com/Up-Mods/Arcanus-Continuum/files/12861580/crash-2023-10-10_14.28.51.9147-quilt_loader.txt)

**Comment by theavandiepen** [comment]
Okay, so, it's looking like the issue isn't just Arcanus. I just tried loading Minecraft with ONLY Sparkweave Engine and qfapi and Minecraft still crashed. I'll report the issue in the github for Sparkweave and put the crash report there

**Comment by UpcraftLP** [comment]
Fixed in Sparkweave v0.3.1

**Comment by theavandiepen** [comment]
Hooray!
