### ISSUE TITLE
Compendium no longer obtainable (1.20.1)

### ISSUE THREAD

**Issue by theavandiepen** [CammiesCorner/Arcanus#12]
Apologies for not reporting this sooner- I was troubleshooting a different mod issue xD

When I open up my save where I had the compendium, it's no longer in my inventory. The /give command doesn't include it as a possible item to give, and it doesn't appear when I check through items using REI.

This is the only error I found in the log mentioning it: 

[15:04:24] [Server thread/WARN] (Minecraft) Invalid statistic in I:\Modrinth Minecraft\profiles\Mods Mods Mods\saves\Ebremic\stats\{MINECRAFT_UUID}.json: Don't know what arcanuscontinuum:compendium_arcanus is

[Here's the whole log](https://mclo.gs/i9A0nSO) in case it's helpful

**Comment by UpcraftLP** [comment]
The compendium is no longer a separate item, it is now using patchouli's default book item.

You can still obtain it if you have patchouli installed, either via the creative tab, by crafting it, or by trading with wizards.

**Comment by theavandiepen** [comment]
Yep, I just sorted that out by looking at the creative inventory and was coming here to let you know xD That said, it would be nice if the crafting recipe could be seen in REI, but I understand if there are technical reasons why that wouldn't work

**Comment by theavandiepen** [comment]
Something else I just noticed, though: the book I just crafted is fully unlocked even though I haven't done anything to unlock things. This happened in a brand new world, too

**Comment by CammiePone** [comment]
that's normal intended behavior

**Comment by UpcraftLP** [comment]
> Yep, I just sorted that out by looking at the creative inventory and was coming here to let you know xD That said, it would be nice if the crafting recipe could be seen in REI, but I understand if there are technical reasons why that wouldn't work

That would likely best be fixed on patchouli's end, rather than having every mod that uses patchouli implement their own handler for it.

**Comment by theavandiepen** [comment]
Makes perfect sense! Thanks for explaining- I really appreciate it :)
