### ISSUE TITLE
Conflict with entity culling

### ISSUE THREAD

**Issue by inmourning** [CammiesCorner/Arcanus#16]
[latest.log](https://github.com/Up-Mods/Arcanus-Continuum/files/13121812/latest.log)
out of range eternal kick on server join
![image](https://github.com/Up-Mods/Arcanus-Continuum/assets/96265940/1548f089-b943-450d-8c52-3b20b6b34a97)

**Comment by UpcraftLP** [comment]
Should be fixed in v0.102.0
