### ISSUE TITLE
Multiple Mana Bars showing up to the party

### ISSUE THREAD

**Issue by EvieTheOwl** [CammiesCorner/Arcanus#17]
![image](https://github.com/Up-Mods/Arcanus-Continuum/assets/46009144/e2502058-ea43-4176-b3d8-2c32148c8f4c)
Look at em go.

**Comment by EvieTheOwl** [comment]
I'll test if it's just happening in my modpack or in the development environment as well soon

**Comment by UpcraftLP** [comment]
Yeah so far I was unable to reproduce this

**Comment by EvieTheOwl** [comment]
Seems fine in the debug environment but not in the modpack I'm using atm. Should be easy enough to debug I'll add some print statements n stuff

**Comment by EvieTheOwl** [comment]
I think I already know what's wrong. If it reads the mana value wrong it becomes more than the max mana value and so the texture repeats. Ideally some kind of system to check if mana > max mana might be handy.

It's working fine now though with the latest fixes in #14 so I'm gonna close this.
