### ISSUE TITLE
Glyphs that modify effects

### ISSUE THREAD

**Issue by LukeAether16** [CammiesCorner/Arcanus#18]
Not only changing the power, but other traits too, like the color of spells, delay of effects, duration of effects and interaction with diferent objects.
These glyphs could be called ''modifiers''.
Thanks for the mod, it have a lot of potential

**Comment by CammiePone** [comment]
so, while modifiers aren't a separate thing, power and duration are determined by how many of the same spell effect are stacked in a given chain. as for different coloured spells, that's a feature for supporters (that i still need to make a non-manual process on my end)
