### ISSUE TITLE
java utils RandomGenerator doesn't exist

### ISSUE THREAD

**Issue by CammiePone** [CammiesCorner/Arcanus#22]
for whatever reason, Prism launcher makes java.utils.RandomGenerartor not have an implementation. thanks Prism

**Comment by UpcraftLP** [comment]
crash log:
[crash-2024-01-20_21.49.02-server.txt](https://github.com/Up-Mods/Arcanus-Continuum/files/13999082/crash-2024-01-20_21.49.02-server.txt)

**Comment by UpcraftLP** [comment]
it appears that some JVM implementations don't provide a default RandomGenerator

either way there's no need to be using that random generator here, as entities already have one.
