### ISSUE TITLE
Scrolls not spawning as loot

### ISSUE THREAD

**Issue by Kuggle01** [CammiesCorner/Arcanus#25]
After loading up a blank instance with just Arcanus, EMI, EMI loot, and the dependancies that those mods have, I can confirm that scrolls of knowledge are not being injected into any loot pools, meaning they can only be obtained via trading. IDK if this is intensional or a bug but either way, I think making scrolls findable as loot and not exclusive obtained through trading would greatly assist the flow of gameplay. Please fix asap

**Comment by CammiePone** [comment]
this is intentional behavior. the scrolls are a developer item that will eventually be replaced with a questing system to increase your level
